### ISSUE TITLE
Feature request: enable toggle input

### ISSUE THREAD

**Issue by falzm** [TomAnthony/itermocil#11]
Could it be possible to implement a feature that toggles the "input broadcasting" on (`⌘⇧I`) in all panes when creating a new session?

**Comment by TomAnthony** [comment]
If you create a script like this, and save it as something link `broadcast.scpt`:

```applescript
tell application "iTerm"
	tell application "System Events" to keystroke "i" using {command down, shift down}
end tell
```

Then you can just run `osascript broadcast.scpt` as a command in one of the panes you open and it would do exactly what you are looking for.

Let me know!
