### ISSUE TITLE
brew error

### ISSUE THREAD

**Issue by berkaey** [TomAnthony/itermocil#117]
I'm getting this.

```Error: Invalid formula: /opt/homebrew/Library/Taps/tomanthony/homebrew-brews/Formula/squid.rb
squid: Calling `sha256 "digest" => :tag` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the tomanthony/brews tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/tomanthony/homebrew-brews/Formula/squid.rb:9

Error: Cannot tap tomanthony/brews: invalid syntax in tap!```

**Comment by melissawimberly** [comment]
Im getting the same error.

**Comment by arioth** [comment]
Same here

**Comment by gsauzande** [comment]
Any workarounds available? I'm also getting this error.

**Comment by LiranBri** [comment]
+1

**Comment by adriangc24** [comment]
Same here

**Comment by hoangvn2404** [comment]
same here

**Comment by gsauzande** [comment]
This worked for me:
Steps:
1- Clone https://github.com/TomAnthony/homebrew-brews
2- Run `brew style --fix Formula` inside that repo
3- Run`brew install --build-from-source ./itermocil.rb`
4- Run `mkdir ~/.itermocil ` then add your `.yml ` files

**Comment by adriangc24** [comment]
This is the only solution worked for me:
1. Uninstall brew -> `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"`
2. Remove local brew files -> `sudo rm -rf /usr/local/Homebrew`
3. Install brew -> `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
4. Update it and run doctor ->` brew update && brew doctor -d`
4. Upgrade `brew upgrade`

**Comment by rinslow** [comment]
Getting it too

**Comment by Zemotacqy** [comment]
Adding to @gsauzande's comment, updated step 3 to:
```
brew install --build-from-source Formula/itermocil.rb
```
We can also ignore the offences generated in step 2.

**Comment by LiranBri** [comment]
@TomAnthony you have any update on this?

**Comment by rogierlommers** [comment]
@TomAnthony , any plans of fixing this?

**Comment by benyitzhaki** [comment]
> This worked for me: Steps: 1- Clone https://github.com/TomAnthony/homebrew-brews 2- Run `brew style --fix Formula` inside that repo 3- Run`brew install --build-from-source ./itermocil.rb` 4- Run `mkdir ~/.itermocil ` then add your `.yml ` files

Thanks! This worked for me. But notice that you need to run the install on the file in the Formula's directory. So instead, do this in step 3:
```
brew install --build-from-source ./Formula/itermocil.rb
```

**Comment by ruudk** [comment]
The problem has been fixed, please run `brew update && brew install tomanthony/brews/itermocil` to retry. 
If you encounter issues, please create a new issue.

**Comment by berkaytheunicorn** [comment]
I guess the problem was (for me at least) running install without `git config --global user.email xx@xx.com`
