### ISSUE TITLE
Installing with homebrew fails 2021-10-15

### ISSUE THREAD

**Issue by krillo** [TomAnthony/itermocil#119]
Your teminal looks good and I would really like to try it, but the installation with brew fails... 
I did the `brew update` first so I have the latest version.
Here's the error:

/Br Krillo

```
💣💣💣 ~ $ brew install TomAnthony/brews/itermocil
==> Tapping tomanthony/brews
Cloning into '/usr/local/Homebrew/Library/Taps/tomanthony/homebrew-brews'...
remote: Enumerating objects: 77, done.
Unpacking objects: 100% (77/77), done.
remote: Total 77 (delta 0), reused 0 (delta 0), pack-reused 77
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/tomanthony/homebrew-brews/Formula/squid.rb
squid: Calling `sha256 "digest" => :tag` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the tomanthony/brews tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/tomanthony/homebrew-brews/Formula/squid.rb:9

Error: Cannot tap tomanthony/brews: invalid syntax in tap!
```

**Comment by rosered90** [comment]
这个一般是由于homebrew出现了问题
解决方案如下：
1、在/usr/local/Homebrew/Library/Taps/目录下新建文件夹名为：tomanthony
2、进入tomanthony文件下：git clone https://github.com/TomAnthony/homebrew-brews

即可～

**Comment by astockwell** [comment]
Thank you @rosered90 !   Translated to English ~

> This is generally due to a problem with homebrew
> The solution is as follows:
> 1. Create a new folder named: tomanthony in the /usr/local/Homebrew/Library/Taps/ directory
> 2. Enter the tomanthony file: git clone https://github.com/TomAnthony/homebrew-brews
> 
> That's it~

**Comment by keyboard-clacker** [comment]
For the people on new M1 Macbooks:

```bash
mkdir -p /opt/homeberw/Library/Taps/tomanthony
git clone https://github.com/TomAnthony/homebrew-brews /opt/homeberw/Library/Taps/tomanthony/homebrew-brews
```

**Comment by swrobel** [comment]
Thanks! However there's a typo and `homebrew` is misspelled in your post. Here is the corrected version:

> For the people on new M1 Macbooks:
> 
> ```shell
> mkdir -p /opt/homebrew/Library/Taps/tomanthony
> git clone https://github.com/TomAnthony/homebrew-brews /opt/homebrew/Library/Taps/tomanthony/homebrew-brews
> ```

**Comment by blakewatson** [comment]
@swrobel @keyboard-clacker why is this required by the new M1 MacBooks?

**Comment by keyboard-clacker** [comment]
Because the homebrew folder is different on apple silicon vs intel cores

**Comment by ruudk** [comment]
@keyboard-clacker Thanks for your hint. Please fix the typo in your post so that it's easier to copy :)

**Comment by alber70g** [comment]
Easier workaround: 

```sh
curl -L https://raw.githubusercontent.com/TomAnthony/homebrew-brews/master/Formula/itermocil.rb > ~/itermocil.rb
brew install ~/itermocil.rb
rm ~/itermocil.rb
```

**Comment by rogierlommers** [comment]
> ```shell
> rm ~/itermocil.rb
> ```

Thanks, @alber70g This indeed works. Would be nice to have the original brew command to work again though.

**Comment by gregorojstersek** [comment]
@alber70g Thank you, the issue was also on an Intel Macbook adn you're workarounds worked like a charm. For other people that would be installing this as well, would be good if the normal instalation would be fixed or at least an easy way to find the solution.

**Comment by Leeiio** [comment]
It doesn't work on M1 MAX with macOS Monterey 12.3 :(
```
→ brew install ~/itermocil.rb
Error: Failed to load cask: /Users/Leeiio/itermocil.rb
Cask 'itermocil' is unreadable: wrong constant name #<Class:0x0000000145126380>
Warning: Treating /Users/Leeiio/itermocil.rb as a formula.
==> Downloading https://pypi.python.org/packages/source/P/PyYAML/PyYAML-3.11.tar.gz
Already downloaded: /Users/Leeiio/Library/Caches/Homebrew/downloads/d98de4b2d4d986c9eacf67d572ad3182da5555a27ae39f38260d899047b9ef4b--PyYAML-3.11.tar.gz
==> Downloading https://github.com/TomAnthony/itermocil/archive/0.2.1.tar.gz
Already downloaded: /Users/Leeiio/Library/Caches/Homebrew/downloads/7660c48dfb6cb50ac68fa581c5de591c2db93fb698776e83084c669a45eb0299--itermocil-0.2.1.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/opt/homebrew/Cellar/itermocil/0.2.1/libexec/vendor --install-scripts=/opt/homebrew/Cellar/itermocil/0.2.1/libexec/vendor/bin --single-version-externally-managed --r
Last 15 lines from /Users/Leeiio/Library/Logs/Homebrew/itermocil/01.python:
2022-03-16 04:49:30 +0000

python
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/opt/homebrew/Cellar/itermocil/0.2.1/libexec/vendor
--install-scripts=/opt/homebrew/Cellar/itermocil/0.2.1/libexec/vendor/bin
--single-version-externally-managed
--record=installed.txt


Do not report this issue to Homebrew/brew or Homebrew/core!
```

> Easier workaround:
> 
> ```shell
> curl -L https://raw.githubusercontent.com/TomAnthony/homebrew-brews/master/Formula/itermocil.rb > ~/itermocil.rb
> brew install ~/itermocil.rb
> rm ~/itermocil.rb
> ```

**Comment by andreikoenig** [comment]
Any solutions to make itermocil work with macOS Monterey 12.3? I dont have M1 and still getting error @Leeiio [Leeiio](https://github.com/Leeiio) posted above.

```
curl -L https://raw.githubusercontent.com/TomAnthony/homebrew-brews/master/Formula/itermocil.rb > ~/itermocil.rb
brew install ~/itermocil.rb
rm ~/itermocil.rb
``` 
This solution did not work for me, still getting the error.

**Comment by gregorojstersek** [comment]
@andreikoenig Here is the issue that would help you - there are number of solutions there, none really clean at the moment - https://github.com/TomAnthony/itermocil/issues/121

**Comment by ruudk** [comment]
The problem has been fixed, please run `brew update && brew install tomanthony/brews/itermocil` to retry. 
If you encounter issues, please create a new issue.
