### ISSUE TITLE
Feature request: check cwd for itermocil file

### ISSUE THREAD

**Issue by mcky** [TomAnthony/itermocil#12]
Just dropped a config file into our projects git repo but running `itermocil --layout itermocil.yml --here` isn't ideal, it'd be nice to be able to drop it into the root like a `.gitignore` or `.editorconfig`

It'd be cool if it was possible to fallback to a check for a file in the current directory if nothing is found in the users root. I'm not a python dev but I can give a shot at a PR to be reviewed if you think it's worthwhile.

Thoughts?

**Comment by TomAnthony** [comment]
Thanks for the suggestion. I'm not against this idea. I am working on some code to add global config so initially I thought this could be a config option, but I don't really see the harm in making it default behaviour to first look in the expected places and then check the others.

**Comment by mcky** [comment]
Cool, shall I have a stab at adding it or do you want to do it in the next
update?

**Comment by TomAnthony** [comment]
It is on my list of things to add and I have a fair idea of how I would do it, but if you are eager to submit a PR then I'm happy with that route too. Otherwise, I expect I'll get to it in the next week or two. :)

**Comment by TomAnthony** [comment]
Thanks!
