### ISSUE TITLE
Alternative way to install it?

### ISSUE THREAD

**Issue by microSoftware** [TomAnthony/itermocil#139]
Hello, i installed/used itermocil years ago (v0.2.1). Sadly this version doesn't work well with my version of iterm (3.4.5). 
I have a macbook 2015 with macos 10.14 and the problem is i can't seem to be able to upgrade it on brew. 
I have a brew message saying i can't upgrade brew or install xcode because of my macos version. 

1/ Is there a manual or alternative way to upgrade itermocil?

Or can i install an old version of itermocil but i can't figure out which one is available on brew: for example: brew install itermocil@0.8

any help please. I really loved itermocil and would love to use it again.

**Comment by godbout** [comment]
you can download any version from the [releases](https://github.com/TomAnthony/itermocil/releases) and put the binary into one of your `PATH` folder and **MAGIC**!

**Comment by microSoftware** [comment]
> you can download any version from the [releases](https://github.com/TomAnthony/itermocil/releases) and put the binary into one of your `PATH` folder and **MAGIC**!

thanks it works

**Comment by godbout** [comment]
welcome. enjoy.
