### ISSUE TITLE
Broken itermocil after 0.1.6 update

### ISSUE THREAD

**Issue by AlecRust** [TomAnthony/itermocil#14]
When updating my brew packages itermocil was bumped to 0.1.6. I'm now receiving this every time I open my terminal or attempt to run `itermocil`:

```sh
Traceback (most recent call last):
  File "/usr/local/Cellar/itermocil/0.1.6/libexec/bin/itermocil", line 3, in <module>
    from itermocil import main
  File "/usr/local/Cellar/itermocil/0.1.6/libexec/bin/itermocil.py", line 8, in <module>
    import yaml
ImportError: No module named yaml
```

Any ideas? My `~/.teamocil` folder remains unchanged after the upgrade.

**Comment by TomAnthony** [comment]
I fixed this earlier today. I think if you run it again (with `brew update` first) then it should be working. Please let me know.

Sorry about that! :)

**Comment by AlecRust** [comment]
Hey @TomAnthony thanks for the reply. There's no new cask update or new version to update to:

```sh
alec at Alec's MacBook in ~
$ brew update
Error: Failed to update tap: caskroom/cask
Already up-to-date.

alec at Alec's MacBook in ~
$ brew install TomAnthony/brews/itermocil
Warning: tomanthony/brews/itermocil-0.1.6 already installed

alec at Alec's MacBook in ~
$ itermocil
Traceback (most recent call last):
  File "/usr/local/Cellar/itermocil/0.1.6/libexec/bin/itermocil", line 3, in <module>
    from itermocil import main
  File "/usr/local/Cellar/itermocil/0.1.6/libexec/bin/itermocil.py", line 8, in <module>
    import yaml
ImportError: No module named yaml
```

**Comment by TomAnthony** [comment]
Oop - sorry, yeah, it is the Formula file that has the error, not itermocil. I've released a new version of itermocil (no changes, just a version bump to get around this issue). If you do `brew update` and `brew install TomAnthony/brews/itermocil` again you should now get the 'new' version and the new Formula file and thus this should be fixed.

Thanks for the fast response earlier. :)

**Comment by AlecRust** [comment]
@TomAnthony after a `brew unlink itermocil` I was able to update to that latest version which fixed it, thank you :+1:

**Comment by TomAnthony** [comment]
Great news - thanks for confirming. :)
