### ISSUE TITLE
It's hard to find a layout matching my needs

### ISSUE THREAD

**Issue by illus0r** [TomAnthony/itermocil#31]
A great project! The thing I was looking for, thanks, @TomAnthony and contributors.

I wanted to use a layout like this:

![image](https://cloud.githubusercontent.com/assets/797993/12537090/f1404170-c2c7-11e5-8710-9b821d270a4e.png)

It's good for watching background scripts and having a focused bottom window for *git*.

Since I didn't find this layout in the `readme.md`, I had to try one by one layouts form the `test-layouts/` directory to came up with `layout: tiled`

What's the better way to find a layout I need?

**Comment by illus0r** [comment]
Oh, sorry, I found [Layouts page](https://github.com/TomAnthony/itermocil/blob/master/LAYOUTS.md)

**Comment by TomAnthony** [comment]
Thanks! :)

You need `main-horizontal` (or `tiled` would also work with 3 panes) - I'm not sure why it is missing from the ReadMe so thanks for leading me to this! :)

**Comment by sassanh** [comment]
@illus0r @TomAnthony how does `tiled` or `main-horizontal` generate above layout? When I use those layouts it puts 2 pans at bottom and one at top. I can't achieve 2 panes at top and one at bottom.
