### ISSUE TITLE
Python version compatibility

### ISSUE THREAD

**Issue by Temaruk** [TomAnthony/itermocil#33]
Great stuff! I have been looking for something to define/automate/version control iTerm layouts! Thank you!

Since I am not using Homebrew, I tried to install via `pip`. That itself works flawlessly, but I could not use the `itermocil` command right away, as upon the first test execution I were receiving a stack trace pointing at the invalid syntax for `print` usage (missing parentheses). Then I realised that I have Python 3.5, and it seems that your script is meant for Python 2.7.

It could have saved me some time and headache if Python version support would have been stated in the docs. It might be useful to add.

**Comment by TomAnthony** [comment]
Good shout. I've just added that now. Thanks. :)
