### ISSUE TITLE
Support iTerm 3.0.0

### ISSUE THREAD

**Issue by ze-phyr-us** [TomAnthony/itermocil#41]
iTerm 3.0.0 is out!

```
$ echo 'get version of application "iTerm"' | osascript
3.0.0
```

Unfortunately this version checking bit does not expect a normal semantic version yet so it bails out thinking the iTerm build is too old: https://github.com/TomAnthony/itermocil/blob/master/itermocil.py#L34

**Comment by bitsapien** [comment]
👍

**Comment by TomAnthony** [comment]
I've pushed a fix for this that appears to be working. Can you verify please @ze-phyr-us. Thanks to @bitsapien. :)

**Comment by mackeyja92** [comment]
@TomAnthony When do you plan on updating this on brew?

**Comment by TomAnthony** [comment]
@mackeyja92 @bitsapien

I've updated that now. Give this a try and let me know:

```bash
# Install `itermocil` via Homebrew
$ brew update
$ brew install TomAnthony/brews/itermocil
```

**Comment by afonsoduarte** [comment]
I've just updated to itermocil 0.2.0 and it still seems to dislike iTerm 3.0.0:

```ShellSession
$ itermocil symposium
This is an unsupported beta build of iTerm.
Try the latest nightly, or the 2.1.1 stable build.
See Readme notes for more info. Sorry!
```

```ShellSession
$ itermocil --version
0.2.0
$ echo 'get version of application "iTerm"' | osascript
3.0.0
```

**Comment by ze-phyr-us** [comment]
Same problem after `brew update && brew upgrade TomAnthony/brews/itermocil`

**Comment by mbollemeijer** [comment]
Same here when using ```80fcb791712c866342a08d6d2520b29a2d69c4cb``` from master branch

**Comment by TomAnthony** [comment]
@ze-phyr-us @mbollemeijer @afonsoduarte Try again now. Sorry - I was on a nightly when testing (need more sleep). :)

**Comment by mbollemeijer** [comment]
Fix confirmed. 👍

**Comment by ze-phyr-us** [comment]
+1, all good!

**Comment by ksingh7** [comment]
+1 Works like charm, Thanks @TomAnthony

**Comment by ryfloyd** [comment]
Even after running `brew upgrade`, my brew formula was stuck on version 0.1.8, I had to explicitly tell brew which formula to execute:

```
brew uninstall itermocil
brew cleanup  # Optional
brew install https://raw.githubusercontent.com/TomAnthony/homebrew-brews/master/Formula/itermocil.rb
```
