### ISSUE TITLE
syntax error: Expected end of line but found class name. (-2741)

### ISSUE THREAD

**Issue by mackeyja92** [TomAnthony/itermocil#43]
I have updated the brew installation to v0.2.1 to support iTerm2 3.0 but I am getting error running what seems to be a really simple panel setup.

Here is my setup

```
10:19:27 ~$ itermocil --show work
windows:
  - name: myserver
    root: ~/
    command: ssh myserver
10:21:05 ~$ itermocil work
163:169: syntax error: Expected end of line but found class name. (-2741)
```

I am just trying to test the water before building my entire config but kept running into this issue. 

I just realized another issue after closing all my iTerm2's and trying again. This time it opens up an iTerm session. I don't understand why it is trying to open up iTerm instead of using the running iTerm2. 

```
10:26:10 ~$ itermocil work
47:53: syntax error: Expected end of line but found class name. (-2741)
```

**Comment by TomAnthony** [comment]
This seems to be a bug in the new function for doing stuff in the current window when only a single command is specified.

I've pushed a fix now - do you want to try that and let me know?

Thanks!

**Comment by TomAnthony** [comment]
Can you run `itermocil --version` to confirm your version number, please.

**Comment by mackeyja92** [comment]
Certainly, it came back with `0.2.1`.

**Comment by mackeyja92** [comment]
@TomAnthony Any update on this? I really want to start using your tools!

**Comment by lotuspond** [comment]
My itermocil version is 0.2.1.
I have same problem.

```
OS X El Capitan : 10.11.6
iTerm2 version : Build 3.0.9
itermocil version : 0.2.1

➜  ~/.itermocil  % itermocil --version
0.2.1
➜  ~/.itermocil  % itermocil ghost4
47:53: syntax error: Expected end of line but found class name. (-2741)
```

**Comment by dmcmanus-usgs** [comment]
If anyone else experiences this, the solution I found was to edit itermocil.py to change iterm to iterm2

**Comment by egglestn** [comment]
I found this because I did not have iTerm2 installed: https://iterm2.com
