### ISSUE TITLE
can you support item2 version 3.0.0

### ISSUE THREAD

**Issue by JackZhang1988** [TomAnthony/itermocil#45]
When i upgrade my iterm2 to 3.0.0, the itermocil not word any more.
The error shows: 

> This is an unsupported beta build of iTerm.
> Try the latest nightly, or the 2.1.1 stable build.
> See Readme notes for more info. Sorry!

Can you make your itermocil support iterm2 3.0.0?

**Comment by mackeyja92** [comment]
This was resolved in #44. You will need to update itermocil.
