### ISSUE TITLE
.itermocil.yml

### ISSUE THREAD

**Issue by inancgumus** [TomAnthony/itermocil#49]
Hi,

`iTermocil.yml` might not be viewable other than the project's own files. This is a common way of storing configuration data as you know from the libraries like, for example, `.babelrc`, `.nvmrc`, `.eslint.rc.js`, `.gitignore` etc.

I think that renaming that file to `.itermocil.yml` would be more user friendly.

What do you think?

**Comment by newbery** [comment]
I second that request.  Or at least allow either filename with the non-hidden version taking precedence.

**Comment by TomAnthony** [comment]
Long time coming, I know, but I added this in https://github.com/TomAnthony/itermocil/commit/7409cdb610370c8d23ef405ece75ef6fbe3a35da. Will be available in the next release.
