### ISSUE TITLE
What do you think about arbitrary layouts

### ISSUE THREAD

**Issue by DomiR** [TomAnthony/itermocil#53]
I would like to implement something like this:

layout: h-1-2
would interpret each number as rows of column

```
*******************************
|                        |                             |
|                        *****************
|                        |                             |  
*******************************
```

layout: v-2-1 
would interpret each number as columns of row

```
*******************************
|                        |                             |
*******************************
|                                                      |  
*******************************
```

What do you think?

**Comment by Frexuz** [comment]
I would love this too :(
I'm using a layout like this

| Col 1: Full height main | Col 2: Split into 3 |
|--|--|
| 0 | 1 |
| 0 | 2 |
| 0 | 3 |

**Comment by psheraton** [comment]
@Frexuz It seems you can use main-vertical layout with 4 panes to accomplish that specific layout.
