### ISSUE TITLE
4 columns?

### ISSUE THREAD

**Issue by chrishough** [TomAnthony/itermocil#65]
Has anyone worked on a 4 or 5 column layout?

**Comment by Didericis** [comment]
I think you can get 4 or 5 columns with a couple of the different layouts (like even-horizontal), but that depends on how many rows you want (see [LAYOUTS.md](https://github.com/TomAnthony/itermocil/blob/master/LAYOUTS.md)). You can do a lot with the different configurations provided, but I had gotten used to a couple particular configurations that I had a hard time creating with itermocil, so I ended up creating [itermp](https://github.com/Didericis/itermp).

**Comment by tcwaddell** [comment]
The following is working for me to create 4, 5, or 6 column layouts with as many rows as needed.

        # '4_columns' layouts create 4 columns and then however many rows as
        # needed. If there are odd number of panes then the bottom pane
        # spans two columns. Panes are numbered top to bottom, left to right.
        elif layout == '4_columns':

            vertical_splits = int(ceil((num_panes / 4.0))) - 1
            second_columns = num_panes / 4
            i = 1

            for p in range(0, vertical_splits):
                pp = (p * 4) + 1
                cp = pp + 4
                i += 1
                self.applescript.append(create_pane(pp, cp, "horizontal"))

            for p in range(0, vertical_splits+1):
                pp = (p * 4) + 1
                for q in range(0, 3):
                    if i >= num_panes:
                        break
                    qp = pp + q
                    cp = pp + 1 + q
                    i += 1
                    self.applescript.append(create_pane(qp, cp, "vertical"))


        # '5_columns' layouts create 5 columns and then however many rows as
        # needed. If there are odd number of panes then the bottom pane
        # spans two columns. Panes are numbered top to bottom, left to right.
        elif layout == '5_columns':

            vertical_splits = int(ceil((num_panes / 5.0))) - 1
            second_columns = num_panes / 5
            i = 1

            for p in range(0, vertical_splits):
                pp = (p * 5) + 1
                cp = pp + 5
                i += 1
                self.applescript.append(create_pane(pp, cp, "horizontal"))

            for p in range(0, vertical_splits+1):
                pp = (p * 5) + 1
                for q in range(0, 4):
                    if i >= num_panes:
                        break
                    qp = pp + q
                    cp = pp + 1 + q
                    i += 1
                    self.applescript.append(create_pane(qp, cp, "vertical"))

        # '6_columns' layouts create 6 columns and then however many rows as
        # needed. If there are odd number of panes then the bottom pane
        # spans two columns. Panes are numbered top to bottom, left to right.
        elif layout == '6_columns':

            vertical_splits = int(ceil((num_panes / 6.0))) - 1
            second_columns = num_panes / 6
            i = 1

            for p in range(0, vertical_splits):
                pp = (p * 6) + 1
                cp = pp + 6
                i += 1
                self.applescript.append(create_pane(pp, cp, "horizontal"))

            for p in range(0, vertical_splits+1):
                pp = (p * 6) + 1
                for q in range(0, 5):
                    if i >= num_panes:
                        break
                    qp = pp + q
                    cp = pp + 1 + q
                    i += 1
                    self.applescript.append(create_pane(qp, cp, "vertical"))
