### ISSUE TITLE
Panes with different roots

### ISSUE THREAD

**Issue by AKFourSeven** [TomAnthony/itermocil#76]
I was wondering if it was possible to have a window with multiple panes that would have different root ? 
By the looks of the read me this seems impossible, however this can be achieved manually in iTerm I thought I might miss something ?

**Comment by mengu** [comment]
@AKFourSeven you can always do:

```
window:
    root: ~/code/project/
    panes:
        rails server
        cd path/relative/to/window/root && lein figwheel
```
