### ISSUE TITLE
Doesn't look in the right folder?

### ISSUE THREAD

**Issue by godbout** [TomAnthony/itermocil#77]
I've created a .itermocil folder, but when I run the edit sample command, itermocil checks for a .teamocil folder.

**Comment by rohan-buchner** [comment]
any luck with this yet?

**Comment by mircsicz** [comment]
For me it was my fault: forgot to add .yml to my tst file in .termocil

**Comment by godbout** [comment]
I don't remember what I did exactly for it to work 😅️

I think I've created the .teamocil folder, then removed it. I didn't have any issue since.

**Comment by ignlg** [comment]
I have this issue too. With a fresh install via homebrew and after creating `~/.itermocil`:

```
$ itermocil --edit foldertest
touch: /Users/ignlg/.teamocil/foldertest.yml: No such file or directory
The file /Users/ignlg/.teamocil/foldertest.yml does not exist.
```

`.teamocil` ?

**Comment by danlangford** [comment]
@ignlg i dont know why its doing what its doing but when i created that folder the command did create a yml file in it. i alsmot wonder if the tool is looking through a list of folders and thats the last one it tries. maybe its a backwards compatibility thing. if you just `touch ~/.itermocil/foldertest.yml` first then your command `itermocil --edit foldertest` will work. absolutely not ideal and a definite bug. but thats your work around.

**Comment by TomAnthony** [comment]
You need to ensure your files have a `.yml` extension. itermocil will look in both `~/.itermocil/` and `~/.teamocil/` directories (in that order).

There is a bug that if you are editing a non-existing file then it will try to create it in `.teamocil` rather than `.itermocil`. I've just fixed this and it'll go out in the next release.

**Comment by supermitch** [comment]
I think a nice easy fix here is to improve the documentation. Just add a line `vi ~/.itermocil/sample.yml`, or add a line saying to first create the file, before running the edit command. 
Or the `--edit` command could simply open a blank file, or even better, generate a sample file if non exists?
