### ISSUE TITLE
Reverse version of main-horizontal and main-vertical

### ISSUE THREAD

**Issue by brandonb927** [TomAnthony/itermocil#8]
First off, I have to say that I love `itermocil` so far! My only gripe is that I wish there was a "reverse" version of the `main-vertical` and `main-horizontal` layouts. Something akin the below example would be amazing:

```
.------------------.------------------.
| (0)              | (2)              |
|                  |                  |
|                  |                  |
|                  |                  |
|------------------|                  |
| (1)              |                  |
|                  |                  |
|                  |                  |
|                  |                  |
'------------------'------------------'
```

Now that being said, I did take a look at the code to see if this was possible so I might try my hand at implementing it in PR myself.

Cheers

**Comment by TomAnthony** [comment]
Hey! Thanks - I'm really glad you are finding it useful.

So - I'm absolutely up for adding that layout. I'm currently working on adding my own file format that adds functionality beyond teamocil files. When I roll that out I'll definitely include this.

If you're impatient to get it added in then I'd welcome a PR! Although I imagine I should get to it in the next week or two (latest). :)

**Comment by brandonb927** [comment]
Fantastic! Maybe I'll hold off and see if that solution addresses my problem. More than willing to field feedback/QA it as well if you're gonna beta test it.

**Comment by febLey** [comment]
I also would like to see this feature

**Comment by febLey** [comment]
https://github.com/TomAnthony/itermocil/pull/10

**Comment by TomAnthony** [comment]
Thanks - I have merged this in. There were a couple of logic errors but I think I've ironed those out and I tested with both versions of iTerm. It'll be available in the next release.

**Comment by brandonb927** [comment]
This is awesome, looking forward to it

**Comment by TomAnthony** [comment]
If you `brew update` and `brew upgrade tomanthony/brews/itermocil` then you should get the new release that has this. Let me know! :)
